"""Initial migration

Revision ID: 92bc3617bcb5
Revises: 
Create Date: 2025-09-21 18:27:34.331613

"""
from alembic import op
import sqlalchemy as sa
import uuid
import sys
import os

# Add the project root to the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import the GUID type from your models
from app.models import GUID
from app.db_utils import JSONEncodedDict


# revision identifiers, used by Alembic.
revision = '92bc3617bcb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('preferred_lesson_length', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('is_quillio_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reset_token')
    )
    op.create_table('courses',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('lesson_id', GUID(), nullable=False),
    sa.Column('course_data', JSONEncodedDict(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_lessons', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('course_id', GUID(), nullable=False),
    sa.Column('unit_title', sa.String(), nullable=False),
    sa.Column('lesson_title', sa.String(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_test_results',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('course_id', GUID(), nullable=False),
    sa.Column('unit_title', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', 'unit_title', name='_user_course_unit_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_test_results')
    op.drop_table('lessons')
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
