"""description of changes

Revision ID: ae1057ee2b98
Revises: 92bc3617bcb5
Create Date: 2025-09-21 18:29:06.277598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1057ee2b98'
down_revision = '92bc3617bcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.String(length=200), nullable=False))
        batch_op.drop_column('lesson_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_column('course_title')

    # ### end Alembic commands ###
