"""Initial migration - baseline from existing database

Revision ID: 05df23a090d7
Revises: 
Create Date: 2025-10-19 15:26:37.014695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '05df23a090d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('unit_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('unit_test_results', schema=None) as batch_op:
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('answers')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('total_questions')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_active')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('unit_test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('answers', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('unit_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###
