"""Add CourseShare model

Revision ID: 50b20d025d9e
Revises: ae1057ee2b98
Create Date: 2025-10-05 15:33:38.079218

"""
from alembic import op
import sqlalchemy as sa
from app.models import GUID


# revision identifiers, used by Alembic.
revision = '50b20d025d9e'
down_revision = 'ae1057ee2b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_shares',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('course_id', GUID(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_shares')
    # ### end Alembic commands ###
