"""rename username to email

Revision ID: c3f7d8e9a1b2
Revises: b2955c2fa2e6
Create Date: 2025-08-27 08:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f7d8e9a1b2'
down_revision = 'b2955c2fa2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username', new_column_name='email', type_=sa.String(length=120))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email', new_column_name='username', type_=sa.String(length=80))

    # ### end Alembic commands ###
