"""Add columns to UnitTestResult

Revision ID: e3da04ffa0f3
Revises: 50b20d025d9e
Create Date: 2025-10-19 11:36:20.371898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e3da04ffa0f3'
down_revision = '50b20d025d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_lessons')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('unit_title')

    with op.batch_alter_table('unit_test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('unit_test_results', schema=None) as batch_op:
        batch_op.drop_column('answers')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('total_questions')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_title', sa.VARCHAR(), nullable=False))

    op.create_table('_alembic_tmp_lessons',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('course_id', sa.CHAR(length=32), nullable=False),
    sa.Column('lesson_title', sa.VARCHAR(), nullable=False),
    sa.Column('html_content', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
