"""Initial migration

Revision ID: f2bf974c4bb0
Revises: 
Create Date: 2025-10-22 18:03:19.627524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f2bf974c4bb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_lessons')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('unit_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('unit_test_results', schema=None) as batch_op:
        batch_op.drop_column('answers')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('total_questions')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_active')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('unit_test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('answers', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('unit_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))

    op.create_table('_alembic_tmp_lessons',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('course_id', sa.CHAR(length=32), nullable=False),
    sa.Column('lesson_title', sa.VARCHAR(), nullable=False),
    sa.Column('html_content', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('unit_title', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
